version: '3.4'

services:
  covidstat.arrivalsdataproducer.worker:
    image: ${DOCKER_REGISTRY-}covidstatarrivalsdataproducerworker
    build:
      context: .
      dockerfile: Services\CovidStat.ArrivalsDataProducer.Worker\Dockerfile

  covidstat.arrivalsdatapublisher.worker:
    image: ${DOCKER_REGISTRY-}covidstatarrivalsdatapublisherworker
    build:
      context: .
      dockerfile: Services\CovidStat.ArrivalsDataPublisher.Worker\Dockerfile
    depends_on:
      - covidstat.arrivals.api

  covidstat.arrivals.api:
    image: ${DOCKER_REGISTRY-}covidstatarrivalsapi
    build:
      context: .
      dockerfile: Web\CovidStat.Arrivals.API\Dockerfile

  covidstat.arrivals.client:
    image: ${DOCKER_REGISTRY-}covidstatarrivalsclient
    build:
        context: .
        dockerfile: Web\CovidStat.Arrivals.Client\Dockerfile
    depends_on:
        - covidstat.arrivals.api

